package projecteuler.p002

// Project Euler
// Problem 2
//
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By 
// starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
// find the sum of the even-valued terms.

object main {
	val fibs: Stream[Int] = 0 #:: 1 #:: (fibs zip fibs.tail).map{case(a,b) => a+b}
	
	def main(args: Array[String]) = {
	  val even_fibs = fibs filter (x => x%2==0) takeWhile (x => x<=4000000);
	  println(even_fibs.sum)
	}
}