//Project Euler
// Problem 2
//
//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By 
//starting with 1 and 2, the first 10 terms will be:
//
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//Find the sum of all the even-valued terms in the sequence which do not exceed four million.

let fib = Seq.unfold (
                      fun state ->
                      if (snd state > 4000000) then None
                      else Some(fst state + snd state, (snd state, fst state + snd state))
    ) (1,1);
let sum = Seq.fold (fun acc i -> if i % 2 = 0 then i + acc else acc) 0 fib;
